build:
    environment:
        node: '0.12.4'

checks:
    php: false
    javascript: true
    python: false
    ruby: false
    java: false

before_commands:
   - npm install

tools:
    js_hint:
        enabled: true
        use_native_config: true
        extensions:
            - js
        config:
            "bitwise"       : false    # Prohibit bitwise operators (& | ^ etc.).
            "node"          : true
application:
    type: none