build:
    environment:
        node: '0.12.4'
        postgresql: false
        rabbitmq: false
        mysql: false
        elasticsearch: false
        php: '5.6.9'

checks:
    php: false

before_commands:
   - npm install

tools:
    js_hint:
        enabled: true
        use_native_config: true
        extensions:
            - js
        config:
            "bitwise"       : false    # Prohibit bitwise operators (& | ^ etc.).
            "node"          : true
application:
    type: none