build:
    environment:
        node: '0.12.4'
        postgresql: false
        rabbitmq: false
        mysql: false
        elasticsearch: false
        redis: false
        php: '5.6.9'
        
tools:
    js_hint:
        enabled: true
        use_native_config: true
        extensions:
            - js
        config:
            "bitwise"       : false    # Prohibit bitwise operators (& | ^ etc.).
            "node"          : true
application:
    type: none